steps:
  - name: gcr.io/kaniko-project/executor:latest
    args: ["--destination=gcr.io/$PROJECT_ID/$_APPLICATION_NAME:$TAG_NAME"]
  - name: trolleksii/git
    entrypoint: /bin/sh
    args: ["./update-config.sh"]
  - name: alpine
    entrypoint: /bin/sh
    args: ["-c", "echo Placeholder for slack notification"]
