steps:
  # - name: gcr.io/cloud-builders/docker
  #   args:
  #     - build
  #     - --tag=gcr.io/$PROJECT_ID/$_APPLICATION_NAME:$SHORT_SHA
  #     - --file=Dockerfile
  #     - "."
  - name: gcr.io/cloud-builders/git
    entrypoint: /bin/sh
    args: ["./update-config.sh"]
  - name: alpine
    entrypoint: /bin/sh
    args: ["-c", "echo Placeholder for slack notification"]
images:
  - gcr.io/$PROJECT_ID/$_APPLICATION_NAME:$SHORT_SHA
