steps:
  - name: gcr.io/cloud-builders/git
    entrypoint: /bin/sh
    args:
      - "-c"
      - |
        echo $TAG_NAME
        git clone https://${_GITHUB_USER}:${_GITHUB_PASSWORD}@github.com/trolleksii/gitops-demo-app.git --branch dev
        cd gitops-demo-app
        git fetch --all --tags
        echo -n "$(git describe --tags)" > /workspace/tag
  - name: gcr.io/cloud-builders/git
    entrypoint: /bin/sh
    args:
      - "-c"
      - |
        git clone https://${_GITHUB_USER}:${_GITHUB_PASSWORD}@github.com/trolleksii/gitops-demo-infra.git --branch dev
        cd gitops-demo-infra
        git config --global user.name "Google Cloud Build"
        git config --global user.email "cbuild@acme.com"
        # update config
        # imitating image tag variable substitution
        sed -i "s/^image_tag = .*$/image_tag = \"$(cat /workspace/tag)\"/g" terraform/main.tfvars
        git add terraform/main.tfvars
        cat <<EOF | git commit -F-
        Update the gitops-demo-app

        This commit updates the container image to:
            gcr.io/${PROJECT_ID}/${_APPLICATION_NAME}:$(cat /workspace/tag).

        Build ID: ${BUILD_ID}
        EOF
        git tag $(cat /workspace/tag)
        git push --tags
        git push
  - name: alpine
    entrypoint: /bin/sh
    args: ["-c", "echo Print URL for PR creation to propagate the environment"]
