steps:
  # - name: gcr.io/kaniko-project/executor:latest
  #   args: ["--destination=gcr.io/$PROJECT_ID/$_APPLICATION_NAME:$TAG_NAME"]
  - name: trolleksii/git
    entrypoint: /bin/sh
    dir: /root
    args:
      - -c
      - |
        git config --global user.email "cbuild@acme.com"
        git config --global user.name "Google Cloud Build"
        echo -n "https://$_GITHUB_USER:$_GITHUB_PASSWORD@github.com/$_GITHUB_USER/gutops-demo-infra.git" > ~/.git-credentials
        git config --global credential.helper 'store --file ~/.git-credentials'
        git clone https://trolleksii@github.com/trolleksii/gutops-demo-infra.git
