steps:
  # - name: gcr.io/kaniko-project/executor:latest
  #   args: ["--destination=gcr.io/$PROJECT_ID/$_APPLICATION_NAME:$TAG_NAME"]
  - name: trolleksii/git
    entrypoint: /bin/sh
    dir: /root
    args:
      - -c
      - |
        git config --global user.email "cbuild@acme.com"
        git config --global user.name "Google Cloud Build"
        echo -n "https://$_GITHUB_USER:$_GITHUB_PASSWORD@github.com/$_GITHUB_USER/gitops-demo-infra.git" > ~/.git-credentials
        git config --global credential.helper 'store --file ~/.git-credentials'
        git clone https://trolleksii@github.com/trolleksii/gitops-demo-infra.git
        cd gitops-demo-infra
        git checkout dev
        # update config
        sed -i "s/^app = .*$/app = \"${TAG_NAME}\"/g" terraform/main.tfvars
        git commit -F- <<EOF
        Update the gitops-demo-app
        This commit updates the container image to:
            gcr.io/${PROJECT_ID}/:${TAG_NAME}.
        Build ID: ${BUILD_ID}
        EOF
        git push origin dev
