steps:
  - name: gcr.io/kaniko-project/executor:latest
    args: ["--destination=gcr.io/${PROJECT_ID}/${APPLICATION_NAME}:${TAG_NAME}"]
  - name: 'trolleksii/git'
    entrypoint: /bin/sh
    args:
      - -c
      - |
        ls -laF
images:
  - gcr.io/${PROJECT_ID}/${APPLICATION_NAME}:${TAG_NAME}
