steps:
  - name: gcr.io/cloud-builders/git
    entrypoint: /bin/sh
    args:
      - "-c"
      - |
        git clone https://$_GITHUB_USER:$_GITHUB_PASSWORD@github.com/trolleksii/gitops-demo-app.git --branch dev
        cd gitops-demo-app
        git fetch --all --tags
        echo -n "$(git describe --tags)" > /workspace/tag
  - name: gcr.io/cloud-builders/docker
    entrypoint: /bin/sh
    args:
      - "-c"
      - docker build --tag=gcr.io/$PROJECT_ID/$_APPLICATION_NAME:$(cat /workspace/tag) --file=Dockerfile .
  - name: gcr.io/cloud-builders/git
    entrypoint: /bin/sh
    args: ["./update-config.sh"]
  - name: alpine
    entrypoint: /bin/sh
    args: ["-c", "echo Placeholder for slack notification"]
images:
  - gcr.io/$PROJECT_ID/$_APPLICATION_NAME:$SHORT_SHA
