resources:
  - name: gitops-demo-app
    type: git
    icon: github
    source:
      uri: https://github.com/trolleksii/gitops-demo-app
      branch: dev
  - name: gitops-demo-infra
    type: git
    icon: github
    source:
      uri: https://github.com/trolleksii/gitops-demo-infra
      branch: dev
  - name: docker-image
    type: docker-image
    source:
      repository: trolleksii/gitops-demo-app
      tag: latest
      username: ((dockerhub_user))
      password: ((dockerhub_password))

jobs:
  - name: build-container
    plan:
      - get: gitops-demo-app
        trigger: true
      - put: docker-image
        params:
          build: gitops-demo-app
  - name: deploy-app
    plan:
      - get: gitops-demo-infra
        trigger: true
      - get: docker-image
        trigger: true
        passed: [build-container]
      - task: deploy-code
        config:
          platform: linux
          inputs:
            - name: docker-image
          image_resource:
            type: docker-image
            source: { repository: alpine }
          run:
            path: cat
            args: ["docker-image/tag"]